"""Add interview_date, keyword_count, note_type, category, and evaluation breakdown scores

Revision ID: b656fb611a90
Revises: '27115f8d8f1e'
Create Date: 2026-07-20 15:32:38.739222

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b656fb611a90'
down_revision: Union[str, None] = '27115f8d8f1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
