from sqlalchemy.orm import Session
from models.mastery import TopicMastery
from models.roadmap import Note
import logging

logger = logging.getLogger("mastery")

def update_topic_mastery(db: Session, user_id: int, topic: str, score_delta: float) -> TopicMastery:
    """
    Updates or creates a TopicMastery record for a user.
    If evaluation flags a weak topic (low score), flags needs_regeneration = True
    and automatically triggers note regeneration.
    """
    mastery = db.query(TopicMastery).filter(
        TopicMastery.user_id == user_id,
        TopicMastery.topic == topic
    ).first()

    if not mastery:
        mastery = TopicMastery(
            user_id=user_id,
            topic=topic,
            mastery_score=max(0.0, min(100.0, 70.0 + score_delta))
        )
        db.add(mastery)
    else:
        mastery.mastery_score = max(0.0, min(100.0, mastery.mastery_score + score_delta))

    if mastery.mastery_score < 70.0:
        mastery.needs_regeneration = True
        enqueue_note_regeneration(db, user_id, topic)

    db.commit()
    db.refresh(mastery)
    return mastery


def enqueue_note_regeneration(db: Session, user_id: int, topic: str):
    """
    Agentic feedback loop: Automatically generates or updates targeted study notes for weak topics.
    """
    logger.info(f"Feedback loop triggered: Generating targeted revision note for user {user_id} on topic '{topic}'")
    existing_note = db.query(Note).filter(
        Note.user_id == user_id,
        Note.topic == topic
    ).first()

    auto_content = (
        f"### Targeted Revision Note: {topic}\n\n"
        f"This revision note was automatically generated by the Evaluation Agent feedback loop "
        f"because performance on **{topic}** was flagged below optimal mastery.\n\n"
        f"**Key Concepts to Review:**\n"
        f"- Core definition & underlying mechanics of {topic}\n"
        f"- Performance trade-offs & edge cases in production\n"
        f"- Common interview questions & best practice implementations."
    )

    if existing_note:
        existing_note.content = auto_content
    else:
        new_note = Note(
            user_id=user_id,
            topic=topic,
            title=f"Refresher: {topic}",
            content=auto_content,
            is_bookmarked=True
        )
        db.add(new_note)
