"""Add JD Analysis, Career Mentor, ATS Score, and Company targeting

Revision ID: 27115f8d8f1e
Revises: 'aa9940455ccf'
Create Date: 2026-07-20 15:28:56.153788

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27115f8d8f1e'
down_revision: Union[str, None] = 'aa9940455ccf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
